name: Transkun Transcription (Manual)

on:
  workflow_dispatch:
    inputs:
      input_path:
        description: 'Path to input mp3 file in the repo'
        required: true
        default: 'input.mp3'

jobs:
  transcribe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Load cached FFmpeg
        id: cache-ffmpeg
        uses: actions/cache@v4
        with:
          path: |
            /usr/local/bin/ffmpeg
            /usr/local/bin/ffprobe
          key: ${{ runner.os }}-ffmpeg-5.1.1

      - name: Install FFmpeg if not cached
        if: steps.cache-ffmpeg.outputs.cache-hit != 'true'
        run: |
          VERSION=5.1.1
          RELEASE_NAME=ffmpeg-${VERSION}-amd64-static
          wget --timeout=8 --tries=30 https://www.johnvansickle.com/ffmpeg/old-releases/${RELEASE_NAME}.tar.xz
          tar -xf ${RELEASE_NAME}.tar.xz
          mv ${RELEASE_NAME}/ffmpeg ${RELEASE_NAME}/ffprobe /usr/local/bin/
          rm -rf ${RELEASE_NAME}


        

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install transkun
        run: pip3 install transkun
      - name: Install audioop-lts
        run: pip3 install audioop-lts
      - name: Run transkun
        run: transkun ${{ github.event.inputs.input_path }} output.mid
      - name: Upload output.mid
        uses: actions/upload-artifact@v4
        with:
          name: output-midi
          path: output.mid
